services:
  fastapi:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    networks:
      - phylo-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket access
      - ./server/data:/app/data
    environment:
      - DATASETS_PATH=${PWD}/server/data/datasets
      - RESULTS_PATH=${PWD}/server/data/results
      - CACHE_PATH=${PWD}/server/data/cache
      - STATIC_PATH=/app/data/results
      - MONGODB_URL=mongodb://mongodb:27017/phylogenetic_jobs
      - LOKI_URL=http://loki:3100
      - LOKI_LOG_LEVEL=debug
      - CONSOLE_LOG_LEVEL=debug
      - LOG_LEVEL=debug
      - FRONTEND_PORT=${FRONTEND_PORT:-8080}
    depends_on:
      - registry
      - mongodb
      - loki

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    networks:
      - phylo-net
    depends_on:
      - fastapi
    environment:
      - BACKEND_URL=http://fastapi:8000

  registry:
    image: registry:2.8.3
    networks:
      - phylo-net
    ports:
      - "${REGISTRY_PORT:-5000}:5000"
    volumes:
      - ./registry-data:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry

  mongodb:
    image: mongo:7.0
    networks:
      - phylo-net
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=phylogenetic_jobs

  loki:
    image: grafana/loki:2.9.0
    networks:
      - phylo-net
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  mongodb_data:
  loki_data:
networks:
  phylo-net:
    driver: bridge
    name: phylo-net
